<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>RedCrow.InsectorTweaks</AssemblyName>
    <RootNamespace>RedCrow.InsectorTweaks</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\1.5\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4104" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.3.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
